repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.0
      hooks:
          - id: ruff
            args: [--fix]
            types: [python]
          - id: ruff-format
            types: [python]

    - repo: local
      hooks:
          - id: pytest
            name: pytest
            entry: uv run pytest
            language: system
            types: [python]
            pass_filenames: false
            always_run: true
