name: Python testing

on:
    push:
        branches:
            - "**"
    pull_request:

jobs:
    build:
        name: Testing on ${{matrix.os}}
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.10", "3.11", "3.12"]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  # setuptools_scm requires a non-shallow clone of the repository
                  fetch-depth: 0

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Python package
              run: |
                  python -m pip install .[tests]

            - name: Run Python tests
              run: |
                  python -m pytest
